// productsData.js

const products = [
       {
      "id": 1,
      "name": "Hồi sức & phòng mổ",
      "price": 1500000,
      "brand": "Humassis",
      "category": "Thiết bị Y tế Bệnh viện",
        "img": "../img/Products/anh1.png",
        "unit": "Bộ", // Ví dụ
        "packaging": "1 bộ/thùng", // Ví dụ
        "model": "RSM-100", // Ví dụ
        "origin": "Hàn Quốc", // Ví dụ
        "description": "Thiết bị hồi sức và phòng mổ hiện đại, đáp ứng các tiêu chuẩn y tế khắt khe." // Ví dụ
     },
     {
      "id": 2,
      "name": "Thiết bị xét nghiệm",
      "price": 5000000,
      "brand": "Humassis",
      "category": "Thiết bị Y tế Bệnh viện",
        "img": "../img/Products/anh2.png",
        "unit": "Máy",
        "packaging": "1 máy/hộp",
        "model": "LAB-2000",
        "origin": "Hàn Quốc",
        "description": "Máy phân tích tự động cho kết quả xét nghiệm nhanh chóng và chính xác."
     },
     {
      "id": 3,
      "name": "Thăm dò chức năng",
      "price": 2000000,
      "brand":"Humassis",
      "category": "Thiết bị Y tế Bệnh viện",
        "img": "../img/Products/anh3.png",
        "unit": "Thiết bị",
        "packaging": "1 thiết bị/hộp",
        "model": "FUNC-300",
        "origin": "Hàn Quốc",
        "description": "Thiết bị hỗ trợ thăm dò và đánh giá chức năng cơ thể."
     },
     {
      "id": 4,
      "name": "Máy đo huyết áp",
      "price": 120000,
      "brand": "Bionet",
      "category": "Thiết bị y tế gia đình",
        "img": "../img/Products/anh4.png",
         "unit": "Cái",
         "packaging": "1 cái/hộp",
         "model": "BP-101",
         "origin": "Đức", // Ví dụ
         "description": "Máy đo huyết áp tự động, dễ sử dụng tại nhà."
     },
     {
      "id": 5,
      "name": "Giường bệnh",
      "price": 7000000,
      "brand": "Hitec",
      "category": "Nội thất Bệnh viện",
        "img": "../img/Products/anh5.png",
         "unit": "Cái",
         "packaging": "1 cái/thùng",
         "model": "GB-PRO",
         "origin": "Việt Nam", // Ví dụ
         "description": "Giường bệnh chắc chắn, có thể điều chỉnh nhiều vị trí."
     },
     {
      "id": 6,
      "name": "Tủ đầu giường bệnh",
      "price": 1500000,
      "brand": "Hitec",
      "category": "Nội thất Bệnh viện",
        "img": "../img/Products/anh6.png",
         "unit": "Cái",
         "packaging": "1 cái/thùng",
         "model": "TB-01",
         "origin": "Việt Nam",
         "description": "Tủ nhỏ gọn đặt đầu giường, tiện lợi cho bệnh nhân."
     },
     {
      "id": 7,
      "name": "Xe lăn",
      "price": 2000000,
      "brand": "Karl Storz",
      "category": "Dụng cụ, vật dụng y tế",
        "img": "../img/Products/anh7.png",
         "unit": "Cái",
         "packaging": "1 cái/hộp",
         "model": "WL-BASIC",
         "origin": "Đức",
         "description": "Xe lăn tiêu chuẩn, khung nhẹ dễ dàng di chuyển."
     },
     {
      "id": 8,
      "name": "Nhiệt kế điện tử",
      "price": 100000,
      "brand": "Bionet",
      "category": "Thiết bị y tế gia đình",
        "img": "../img/Products/anh8.png",
         "unit": "Cái",
         "packaging": "1 cái/vỉ",
         "model": "TK-DIGI",
         "origin": "Đức",
         "description": "Nhiệt kế đo nhanh và chính xác."
     },
     {
      "id": 9,
      "name": "Máy trợ thính",
      "price": 2500000,
      "brand": "Hitec",
      "category": "Thiết bị y tế gia đình",
        "img": "../img/Products/anh9.png",
         "unit": "Cái",
         "packaging": "1 cái/hộp",
         "model": "MT-COMPACT",
         "origin": "Việt Nam",
         "description": "Máy trợ thính nhỏ gọn, âm thanh rõ nét."
     },
     {
      "id": 10,
      "name": "Máy đo huyết áp điện tử",
      "price": 300000,
      "brand": "Hitec",
      "category": "Thiết bị y tế gia đình",
        "img": "../img/Products/anh10.png",
         "unit": "Cái",
         "packaging": "1 cái/hộp",
         "model": "HA-SMART",
         "origin": "Việt Nam",
         "description": "Máy đo huyết áp điện tử có màn hình hiển thị lớn."
     },
     {
      "id": 11,
      "name": "Máy kích dung, hút dịch",
      "price": 4000000,
      "brand": "Karl Storz",
      "category": "Thiết bị Y tế Bệnh viện",
        "img": "../img/Products/anh11.png",
         "unit": "Máy",
         "packaging": "1 máy/thùng",
         "model": "SD-500",
         "origin": "Đức",
         "description": "Thiết bị y tế chuyên dụng cho hút dịch."
     },
     {
      "id": 12,
      "name": "Kim luồn, khóa ba chạc",
      "price": 50000,
      "brand": "Bionet",
      "category": "Vật tư y tế chuyên khoa",
        "img": "../img/Products/anh12.png",
         "unit": "Vỉ",
         "packaging": "10 vỉ/hộp",
         "model": "KL-01",
         "origin": "Đức",
         "description": "Vật tư y tế dùng trong truyền dịch."
     },
     {
      "id": 13,
      "name": "Kim châm cứu",
      "price": 20000,
      "brand": "Hitec",
      "category": "Dụng cụ, vật dụng y tế",
        "img": "../img/Products/anh13.png",
         "unit": "Hộp",
         "packaging": "100 kim/hộp",
         "model": "KC-A",
         "origin": "Việt Nam",
         "description": "Kim châm cứu dùng một lần, vô trùng."
     },
     {
      "id": 14,
      "name": "Găng tay y tế",
      "price": 100000,
      "brand": "Humassis",
      "category": "Vật tư y tế cơ bản",
        "img": "../img/Products/anh14.png",
         "unit": "Hộp",
         "packaging": "100 cái/hộp",
         "model": "GT-LATEX",
         "origin": "Hàn Quốc",
         "description": "Găng tay cao su y tế, size M."
     },
     {
      "id": 15,
      "name": "Ống sonde, dây dẫn",
      "price": 80000,
      "brand": "Medel",
      "category": "Vật tư y tế chuyên khoa",
        "img": "../img/Products/anh15.png",
         "unit": "Cái",
         "packaging": "1 cái/gói",
         "model": "SD-TUBE",
         "origin": "Ý", // Ví dụ
         "description": "Ống sonde y tế chuyên dụng."
     },
     {
      "id": 16,
      "name": "Hóa chất, sinh phẩm",
      "price": 150000,
      "brand": "Medel",
      "category": "Hóa chất, sinh phẩm",
        "img": "../img/Products/anh16.png",
         "unit": "Hộp",
         "packaging": "Theo quy cách",
         "model": "HCSP-01",
         "origin": "Ý",
         "description": "Hóa chất dùng trong phòng xét nghiệm."
     },
     {
      "id": 17,
      "name": "Test nhanh",
      "price": 300000,
      "brand": "Medel",
      "category": "Hóa chất, sinh phẩm",
        "img": "../img/Products/anh17.png",
         "unit": "Hộp",
         "packaging": "25 test/hộp",
         "model": "TEST-COVID",
         "origin": "Ý",
         "description": "Bộ kit test nhanh phát hiện kháng nguyên."
     },
     {
      "id": 18,
      "name": "Dung dịch xịt mũi",
      "price": 70000,
      "brand": "Medel",
      "category": "Vật tư y tế cơ bản",
        "img": "../img/Products/anh18.png",
         "unit": "Chai",
         "packaging": "1 chai/hộp",
         "model": "XM-PHYSIO",
         "origin": "Ý",
         "description": "Dung dịch nước muối sinh lý xịt mũi."
     },
     {
      "id": 19,
      "name": "Dược phẩm",
      "price": 120000,
      "brand": "Trustmed",
      "category": "Vật tư y tế cơ bản",
        "img": "../img/Products/anh19.png",
         "unit": "Hộp",
         "packaging": "Theo quy cách",
         "model": "DRUG-A",
         "origin": "Việt Nam", // Ví dụ
         "description": "Sản phẩm dược phẩm hỗ trợ điều trị."
     },
     {
      "id": 20,
      "name": "Lòng ấp cho trẻ sơ sinh",
      "price": 10000000,
      "brand": "Humassis",
      "category": "Thiết bị Y tế Bệnh viện",
        "img": "../img/Products/anh20.png",
         "unit": "Cái",
         "packaging": "1 cái/thùng",
         "model": "INC-BABY",
         "origin": "Hàn Quốc",
         "description": "Thiết bị y tế chuyên dụng cho trẻ sơ sinh."
     },
     {
      "id": 21,
      "name": "Dụng cụ trị liệu",
      "price": 500000,
      "brand": "Trustmed",
      "category": "Dụng cụ, vật dụng y tế",
        "img": "../img/Products/anh21.png",
         "unit": "Bộ",
         "packaging": "1 bộ/hộp",
         "model": "TRP-SET",
         "origin": "Việt Nam",
         "description": "Bộ dụng cụ hỗ trợ phục hồi chức năng."
     },
     {
      "id": 22,
      "name": "Bộ truyền giảm đau",
      "price": 2000000,
      "brand": "Trustmed",
      "category": "Vật tư y tế chuyên khoa",
        "img": "../img/Products/anh22.png",
         "unit": "Bộ",
         "packaging": "1 bộ/gói",
         "model": "PAIN-RELIEF",
         "origin": "Việt Nam",
         "description": "Bộ thiết bị dùng trong giảm đau y tế."
     },
     {
      "id": 23,
      "name": "Máy điện tim 12 kênh Bionet Cardio Q50",
      "price": 81000000,
      "brand": "Bionet",
      "category": "Thiết bị Y tế Bệnh viện",
        "img": "../img/Products/anh23.png",
         "unit": "Máy",
         "packaging": "1 máy/thùng",
         "model": "Cardio Q50",
         "origin": "Đức",
         "description": "Máy điện tim chất lượng cao cho kết quả chính xác."
     },
     {
      "id": 24,
      "name": "Máy monitor theo dõi bệnh nhân Bionet Brio X50",
      "price": 78300000,
      "brand": "Bionet",
      "category": "Thiết bị Y tế Bệnh viện",
        "img": "../img/Products/anh24.png",
         "unit": "Máy",
         "packaging": "1 máy/thùng",
         "model": "Brio X50",
         "origin": "Đức",
         "description": "Máy theo dõi các chỉ số sức khỏe của bệnh nhân."
     },
     {
      "id": 25,
      "name": "Máy đo huyết áp điện tử bắp tay Humed HM-A9",
      "price": 712000,
      "brand": "Humed",
      "category": "Thiết bị y tế gia đình",
        "img": "../img/Products/anh25.png",
         "unit": "Cái",
         "packaging": "1 cái/hộp",
         "model": "HM-A9",
         "origin": "Hàn Quốc",
         "description": "Máy đo huyết áp bắp tay dùng tại nhà."
     },
     {
      "id": 26,
      "name": "Máy điện tim 12 kênh Bionet Cardio Q70",
      "price": 91800000,
      "brand": "Bionet",
      "category": "Thiết bị Y tế Bệnh viện",
        "img": "../img/Products/anh26.png",
         "unit": "Máy",
         "packaging": "1 máy/thùng",
         "model": "Cardio Q70",
         "origin": "Đức",
         "description": "Máy điện tim chuyên nghiệp với 12 kênh."
     },
     {
      "id": 27,
      "name": "Máy monitor theo dõi bệnh nhân Bionet Brio X70",
      "price": 8910000,
      "brand": "Bionet",
      "category": "Thiết bị Y tế Bệnh viện",
        "img": "../img/Products/anh27.png",
         "unit": "Máy",
         "packaging": "1 máy/thùng",
         "model": "Brio X70",
         "origin": "Đức",
         "description": "Máy monitor cao cấp theo dõi nhiều thông số cùng lúc."
     },
     {
      "id": 28,
      "name": "Máy thở không xâm lấn cao cấp 3 in 1 Mekics HFT700",
      "price": 140000000,
      "brand": "Mekics",
      "category": "Thiết bị Y tế Bệnh viện",
        "img": "../img/Products/anh28.png",
         "unit": "Máy",
         "packaging": "1 máy/thùng",
         "model": "HFT700",
         "origin": "Hàn Quốc", // Ví dụ
         "description": "Máy thở hỗ trợ hô hấp không xâm lấn."
     },
     {
      "id": 29,
      "name": "Máy monitor theo dõi bệnh nhân Bionet Brio X30",
      "price": 67500000,
      "brand": "Bionet",
      "category": "Thiết bị Y tế Bệnh viện",
        "img": "../img/Products/anh29.png",
         "unit": "Máy",
         "packaging": "1 máy/thùng",
         "model": "Brio X30",
         "origin": "Đức",
         "description": "Máy monitor cơ bản, dễ sử dụng."
     },
     {
      "id": 30,
      "name": "Máy xét nghiệm huyết học tự động 3 thành phần Rayto RT-7600",
      "price": 128250000,
      "brand": "Rayto",
      "category": "Thiết bị Y tế Bệnh viện",
        "img": "../img/Products/anh30.png",
         "unit": "Máy",
         "packaging": "1 máy/thùng",
         "model": "RT-7600",
         "origin": "Trung Quốc", // Ví dụ
         "description": "Máy xét nghiệm huyết học phân tích 3 thành phần."
     },
     {
      "id": 31,
      "name": "Máy huyết áp để bàn chuyên dụng cho bệnh viện Accuniq BP500",
      "price": 52000000,
      "brand": "Accuniq",
      "category": "Thiết bị Y tế Bệnh viện",
        "img": "../img/Products/anh31.png",
         "unit": "Máy",
         "packaging": "1 máy/hộp",
         "model": "BP500",
         "origin": "Hàn Quốc", // Ví dụ
         "description": "Máy đo huyết áp chuyên nghiệp dùng trong bệnh viện."
     },
     {
      "id": 32,
      "name": "Máy đo độ bão hòa oxy máu cao cấp Medel OXYGEN PO01",
      "price": 920000,
      "brand": "Medel",
      "category": "Thiết bị y tế gia đình",
        "img": "../img/Products/anh32.png",
         "unit": "Cái",
         "packaging": "1 cái/hộp",
         "model": "OXYGEN PO01",
         "origin": "Ý",
         "description": "Máy đo SpO2 nhỏ gọn, kết quả nhanh."
     },
     {
      "id": 33,
      "name": "Máy thở oxy dòng cao HFNC hiện đại Mekics HFT500",
      "price": 108000000,
      "brand": "Mekics",
      "category": "Thiết bị Y tế Bệnh viện",
        "img": "../img/Products/anh33.png",
         "unit": "Máy",
         "packaging": "1 máy/thùng",
         "model": "HFT500",
         "origin": "Hàn Quốc",
         "description": "Máy cung cấp oxy dòng cao, hỗ trợ hô hấp hiệu quả."
     },
     {
      "id": 34,
      "name": "Máy sinh hóa máu tự động Rayto Chemray 420",
      "price": 47250000,
      "brand": "Rayto",
      "category": "Thiết bị Y tế Bệnh viện",
        "img": "../img/Products/anh34.png",
         "unit": "Máy",
         "packaging": "1 máy/thùng",
         "model": "Chemray 420",
         "origin": "Trung Quốc",
         "description": "Máy phân tích sinh hóa máu tự động."
     },
     {
      "id": 35,
      "name": "Máy đo đường huyết Accu-Chek Instant",
      "price": 960000,
      "brand": "Accu-Chek",
      "category": "Thiết bị y tế gia đình",
        "img": "../img/Products/anh35.png",
         "unit": "Bộ",
         "packaging": "1 bộ/hộp",
         "model": "Instant",
         "origin": "Đức", // Ví dụ
         "description": "Máy đo đường huyết cho kết quả tức thì."
     },
     {
      "id": 36,
      "name": "Máy đo đường huyết Accu-Chek Performa",
      "price": 1040000,
      "brand": "Accu-Chek",
      "category": "Thiết bị y tế gia đình",
        "img": "../img/Products/anh36.png",
         "unit": "Bộ",
         "packaging": "1 bộ/hộp",
         "model": "Performa",
         "origin": "Đức",
         "description": "Máy đo đường huyết với độ chính xác cao."
     },
     {
      "id": 37,
      "name": "Máy đo đường huyết Accu-Chek Active",
      "price": 880000,
      "brand": "Accu-Chek",
      "category": "Thiết bị y tế gia đình",
        "img": "../img/Products/anh37.png",
         "unit": "Bộ",
         "packaging": "1 bộ/hộp",
         "model": "Active",
         "origin": "Đức",
         "description": "Máy đo đường huyết phổ biến, dễ sử dụng."
     },
     {
      "id": 38,
      "name": "Máy đo đường huyết Glucometer Elite",
      "price": 1200000,
      "brand": "Glucometer",
      "category": "Thiết bị y tế gia đình",
        "img": "../img/Products/anh38.png",
         "unit": "Bộ",
         "packaging": "1 bộ/hộp",
         "model": "Elite",
         "origin": "Mỹ", // Ví dụ
         "description": "Máy đo đường huyết nhỏ gọn, tiện lợi."
     },
     {
      "id": 39,
      "name": "Máy đo đường huyết Glucometer WaveSense Jazz",
      "price": 1280000,
      "brand": "Glucometer WaveSense",
      "category": "Thiết bị y tế gia đình",
        "img": "../img/Products/anh39.png",
         "unit": "Bộ",
         "packaging": "1 bộ/hộp",
         "model": "Jazz",
         "origin": "Mỹ",
         "description": "Máy đo đường huyết công nghệ WaveSense."
     },
     {
      "id": 40,
      "name": "Máy đo đường huyết Glucometer WaveSense Keynote",
      "price": 1360000,
      "brand": "Glucometer WaveSense",
      "category": "Thiết bị y tế gia đình",
        "img": "../img/Products/anh40.png",
         "unit": "Bộ",
         "packaging": "1 bộ/hộp",
         "model": "Keynote",
         "origin": "Mỹ",
         "description": "Máy đo đường huyết có bộ nhớ lớn."
     },
     {
      "id": 41,
      "name": "Máy đo đường huyết Glucometer WaveSense Presto",
      "price": 1440000,
      "brand": "Glucometer WaveSense",
      "category": "Thiết bị y tế gia đình",
        "img": "../img/Products/anh41.png",
         "unit": "Bộ",
         "packaging": "1 bộ/hộp",
         "model": "Presto",
         "origin": "Mỹ",
         "description": "Máy đo đường huyết cho kết quả nhanh trong vài giây."
     },
     {
      "id": 42,
      "name": "Máy đo đường huyết Glucometer WaveSense Optium Exa",
      "price": 1520000,
      "brand": "Glucometer WaveSense",
      "category": "Thiết bị y tế gia đình",
        "img": "../img/Products/anh42.png",
         "unit": "Bộ",
         "packaging": "1 bộ/hộp",
         "model": "Optium Exa",
         "origin": "Mỹ",
         "description": "Máy đo đường huyết với que thử tiện lợi."
     },
     {
      "id": 43,
      "name": "Máy đo đường huyết Glucometer WaveSense Optium Xceed",
      "price": 1600000,
      "brand": "Glucometer WaveSense",
      "category": "Thiết bị y tế gia đình",
        "img": "../img/Products/anh43.png",
         "unit": "Bộ",
         "packaging": "1 bộ/hộp",
         "model": "Optium Xceed",
         "origin": "Mỹ",
         "description": "Máy đo đường huyết tích hợp đèn nền."
     },
     {
      "id": 44,
      "name": "Máy đo đường huyết Glucometer WaveSense Optium Xceed Plus",
      "price": 1680000,
      "brand": "Glucometer WaveSense",
      "category": "Thiết bị y tế gia đình",
      "img":"../img/Products/anh44.png",
        "unit": "Bộ",
        "packaging": "1 bộ/hộp",
        "model": "Optium Xceed Plus",
        "origin": "Mỹ",
        "description": "Máy đo đường huyết cao cấp, kết nối dữ liệu."
     }
    ];